name: Github Conditional workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test-conditionals:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for documentation-only changes
      id: check-docs
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -vE '^(docs/|README\.md)$'; then
           echo "not-docs=true" >> $GITHUB_ENV
        else
           echo "not-docs=false" >> $GITHUB_ENV

    - name: run test
      if: env.not-docs == 'true' && contains(github.event.pull_request.labels.*.name, 'run-tests')
      run: echo "Running tests"
